# Generated by Django 4.1.7 on 2023-05-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0003_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='type',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
