# Generated by Django 4.1.7 on 2023-05-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0006_alter_course_urladd_tempattendance_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.CharField(max_length=20),
        ),
    ]
