# Generated by Django 4.1.7 on 2023-05-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0009_attendance_faculty_id_tempattendance_faculty_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherqr',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherqr',
            name='end_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherqr',
            name='start_time',
            field=models.CharField(max_length=10),
        ),
    ]
