# Generated by Django 4.1.7 on 2023-05-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0010_alter_teacherqr_date_alter_teacherqr_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherqr',
            name='end_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherqr',
            name='start_time',
            field=models.CharField(max_length=20),
        ),
    ]
